{"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/1342/comments/13874854.json"}, "html": {"href": "#!/osrf/gazebo/issues/1342#comment-13874854"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/1342.json"}}, "type": "issue", "id": 1342, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "System fails to run all of a sudden (on file that ran fine moments before) from seemingly outside (packages) cause."}, "content": {"raw": null, "markup": "markdown", "html": "", "type": "rendered"}, "created_on": "2014-11-26T00:33:02.999412+00:00", "user": {"display_name": "James Taylor", "uuid": "{80a5efd1-140d-4624-a75d-d114628c1db8}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B80a5efd1-140d-4624-a75d-d114628c1db8%7D"}, "html": {"href": "https://bitbucket.org/%7B80a5efd1-140d-4624-a75d-d114628c1db8%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/3cbda94bb60d047f7d10c50d7d847d5ed=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJT-3.png"}}, "nickname": "jrtaylor", "type": "user", "account_id": "557058:e8ac7e8b-59fe-4119-a528-7d0f5b851e6e"}, "updated_on": null, "type": "issue_comment", "id": 13874854}