{"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2356/comments/40369987.json"}, "html": {"href": "#!/osrf/gazebo/issues/2356#comment-40369987"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2356.json"}}, "type": "issue", "id": 2356, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "Build with boost 1.58.0 error"}, "content": {"raw": "I found this #1399, but I still got the error with boost 1.58.0", "markup": "markdown", "html": "<p>I found this <a href=\"#!/osrf/gazebo/issues/1399/build-fails-with-boost-157\" rel=\"nofollow\" title=\"Build fails with Boost 1.57\" class=\"ap-connect-link\"><s>#1399</s></a>, but I still got the error with boost 1.58.0</p>", "type": "rendered"}, "created_on": "2017-10-07T04:27:19.679012+00:00", "user": {"display_name": "Jack Liu", "uuid": "{81945f98-d7ff-46f8-a856-bcfe6bcce018}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B81945f98-d7ff-46f8-a856-bcfe6bcce018%7D"}, "html": {"href": "https://bitbucket.org/%7B81945f98-d7ff-46f8-a856-bcfe6bcce018%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/17e5b42085cfb1e0593692b4e30e9ed6d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJL-0.png"}}, "nickname": "jacknlliu", "type": "user", "account_id": "557058:4ff52431-cce6-42f3-bf55-fefe6d5678ce"}, "updated_on": null, "type": "issue_comment", "id": 40369987}