{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "links": {"attachments": {"href": "data/repositories/osrf/gazebo/issues/1059/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/gazebo/issues/1059.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gazebo/issues/1059/watch"}, "comments": {"href": "data/repositories/osrf/gazebo/issues/1059/comments_page=1.json"}, "html": {"href": "#!/osrf/gazebo/issues/1059/occasional-unit_gpssensor_test-failure"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gazebo/issues/1059/vote"}}, "reporter": {"display_name": "Steve Peters", "uuid": "{2ccfed09-18b8-4921-8d58-15ef01092802}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D"}, "html": {"href": "https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/1fb4816dad9e68337d3096f750951f6cd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSP-1.png"}}, "nickname": "Steven Peters", "type": "user", "account_id": "557058:5de38267-b118-494c-aa76-4fab35448816"}, "title": "Occasional UNIT_GpsSensor_TEST failure", "component": null, "votes": 0, "watches": 1, "content": {"raw": "[Occasional UNIT_GpsSensor_TEST failure in Jenkins](http://build.osrfoundation.org/job/gazebo-default-devel-quantal-amd64-gpu-nvidia/535/testReport/junit/(root)/UNIT_GpsSensor_TEST/test_ran/) (the following build did not fail). It has the following console error:\r\n~~~\r\n103: [==========] Running 1 test from 1 test case.\r\n103: [----------] Global test environment set-up.\r\n103: [----------] 1 test from GpsSensor_TEST\r\n103: [ RUN      ] GpsSensor_TEST.CreateGps\r\n103: UNIT_GpsSensor_TEST: /usr/include/boost/smart_ptr/shared_ptr.hpp:424: T* boost::shared_ptr<T>::operator->() const [with T = gazebo::sensors::Noise]: Assertion `px != 0' failed.\r\n103: [Msg] \u001bWaiting for master.\u001b\r\n103: \u001b\u001b[Msg] \u001bConnected to gazebo master @ \u001bhttp://127.0.0.1:11345\u001b\r\n103: \u001b\u001b[Msg] \u001bPublicized address: \u001b192.168.1.196\u001b\r\n103: \u001b\u001b\u001b[Dbg] \u001b\u001b[\u001b\u001bServerFixture.cc\u001b\u001b:\u001b\u001b144\u001b\u001b] \u001b\u001bServerFixture load in \u001b\u001b1.1\u001b\u001b seconds, timeout after \u001b\u001b600\u001b\u001b seconds\r\n103: \u001b\u001b[Dbg] \u001b\u001b[\u001b\u001bServerFixture.cc\u001b\u001b:\u001b\u001b95\u001b\u001b] \u001b\u001bServerFixture::Unload\u001b\u001b\r\n103: \u001b\u001b\u001b\r\n103/130 Test #103: UNIT_GpsSensor_TEST ....................***Exception: Other 10.94 sec\r\n~~~\r\n\r\nIt happens very early in the test. A backtrace on my mac (where it fails very consistently) implicates the following line in [GpsSensor::UpdateImpl](#!/osrf/gazebo/src/c3f5afdbd905d03a326d5d4fb762421edc0a15aa/gazebo/sensors/GpsSensor.cc#cl-142):\r\n~~~\r\n-> 142 \t      gpsVelocity.x = this->horizontalVelocityNoise->Apply(gpsVelocity.x);\r\n~~~\r\n\r\nThe noise data structures get allocated in `GpsSensor::Load` as of pull request #936, so I'm guessing that the Sensor update loops are being started before everything has loaded properly.", "markup": "markdown", "html": "<p><a data-is-external-link=\"true\" href=\"http://build.osrfoundation.org/job/gazebo-default-devel-quantal-amd64-gpu-nvidia/535/testReport/junit/(root)/UNIT_GpsSensor_TEST/test_ran/\" rel=\"nofollow\">Occasional UNIT_GpsSensor_TEST failure in Jenkins</a> (the following build did not fail). It has the following console error:</p>\n<div class=\"codehilite\"><pre><span></span>103: [==========] Running 1 test from 1 test case.\n103: [----------] Global test environment set-up.\n103: [----------] 1 test from GpsSensor_TEST\n103: [ RUN      ] GpsSensor_TEST.CreateGps\n103: UNIT_GpsSensor_TEST: /usr/include/boost/smart_ptr/shared_ptr.hpp:424: T* boost::shared_ptr&lt;T&gt;::operator-&gt;() const [with T = gazebo::sensors::Noise]: Assertion `px != 0&#39; failed.\n103: [Msg] \u001bWaiting for master.\u001b\n103: \u001b\u001b[Msg] \u001bConnected to gazebo master @ \u001bhttp://127.0.0.1:11345\u001b\n103: \u001b\u001b[Msg] \u001bPublicized address: \u001b192.168.1.196\u001b\n103: \u001b\u001b\u001b[Dbg] \u001b\u001b[\u001b\u001bServerFixture.cc\u001b\u001b:\u001b\u001b144\u001b\u001b] \u001b\u001bServerFixture load in \u001b\u001b1.1\u001b\u001b seconds, timeout after \u001b\u001b600\u001b\u001b seconds\n103: \u001b\u001b[Dbg] \u001b\u001b[\u001b\u001bServerFixture.cc\u001b\u001b:\u001b\u001b95\u001b\u001b] \u001b\u001bServerFixture::Unload\u001b\u001b\n103: \u001b\u001b\u001b\n103/130 Test #103: UNIT_GpsSensor_TEST ....................***Exception: Other 10.94 sec\n</pre></div>\n\n\n<p>It happens very early in the test. A backtrace on my mac (where it fails very consistently) implicates the following line in <a data-is-external-link=\"true\" href=\"#!/osrf/gazebo/src/c3f5afdbd905d03a326d5d4fb762421edc0a15aa/gazebo/sensors/GpsSensor.cc#cl-142\" rel=\"nofollow\">GpsSensor::UpdateImpl</a>:</p>\n<div class=\"codehilite\"><pre><span></span>-&gt; 142        gpsVelocity.x = this-&gt;horizontalVelocityNoise-&gt;Apply(gpsVelocity.x);\n</pre></div>\n\n\n<p>The noise data structures get allocated in <code>GpsSensor::Load</code> as of <a href=\"#!/osrf/gazebo/pull-requests/936/fix-noise-test-take-2\" rel=\"nofollow\" class=\"ap-connect-link\">pull request #936</a>, so I'm guessing that the Sensor update loops are being started before everything has loaded properly.</p>", "type": "rendered"}, "assignee": null, "state": "closed", "version": {"name": "all", "links": {"self": {"href": "data/repositories/osrf/gazebo/versions/225575.json"}}}, "edited_on": null, "created_on": "2014-02-21T02:46:20.718817+00:00", "milestone": null, "updated_on": "2016-09-14T19:43:31.927452+00:00", "type": "issue", "id": 1059}