{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "links": {"attachments": {"href": "data/repositories/osrf/gazebo/issues/1480/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/gazebo/issues/1480.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gazebo/issues/1480/watch"}, "comments": {"href": "data/repositories/osrf/gazebo/issues/1480/comments_page=1.json"}, "html": {"href": "#!/osrf/gazebo/issues/1480/unit_exception_test-failure-on-os-x"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gazebo/issues/1480/vote"}}, "reporter": {"display_name": "Steve Peters", "uuid": "{2ccfed09-18b8-4921-8d58-15ef01092802}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D"}, "html": {"href": "https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/1fb4816dad9e68337d3096f750951f6cd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSP-1.png"}}, "nickname": "Steven Peters", "type": "user", "account_id": "557058:5de38267-b118-494c-aa76-4fab35448816"}, "title": "UNIT_Exception_TEST failure on OS X", "component": {"name": "os::osx", "links": {"self": {"href": "data/repositories/osrf/gazebo/components/126618.json"}}}, "votes": 0, "watches": 1, "content": {"raw": "[UNIT_Exception_TEST is failing](http://build.osrfoundation.org/job/gazebo-any-devel-homebrew-amd64/493/testReport/(root)/Exception/GZASSERT_Enabled_ThrowAssertion/) on OS X consistently. Here is the console output:\r\n\r\n~~~\r\n55: [ RUN      ] Exception.GZASSERT_Enabled_ThrowAssertion\r\n55:\r\n55: [WARNING] /Users/jenkins/workspace/gazebo-any-devel-homebrew-amd64/gazebo/test/gtest/src/gtest-death-test.cc:825:: Death tests use fork(), which is unsafe particularly in a threaded context. For this test, Google Test detected 2 threads.\r\n55: /Users/jenkins/workspace/gazebo-any-devel-homebrew-amd64/gazebo/gazebo/common/Exception_TEST.cc:81: Failure\r\n55: Death test: (__builtin_expect(!((true == false)&&(\"Assert thrown\")), 0) ? __assert_rtn(__func__, \"/Users/jenkins/workspace/gazebo-any-devel-homebrew-amd64/gazebo/gazebo/common/Exception_TEST.cc\", 80, \"(true == false)&&(\\\"Assert thrown\\\")\") : (void)0)\r\n55:     Result: died but not with expected error.\r\n55:   Expected: .*Internal Program Error - assertion.*\r\n55: Actual msg:\r\n55: [  DEATH   ] Assertion failed: ((true == false)&&(\"Assert thrown\")), function TestBody, file /Users/jenkins/workspace/gazebo-any-devel-homebrew-amd64/gazebo/gazebo/common/Exception_TEST.cc, line 80.\r\n55: [  DEATH   ] \r\n55: [  FAILED  ] Exception.GZASSERT_Enabled_ThrowAssertion (15162 ms)\r\n~~~\r\n\r\nOn trusty, the console output looks like this:\r\n~~~\r\n55: [ RUN      ] Exception.GZASSERT_Enabled_ThrowAssertion\r\n55:\r\n55: [WARNING] /var/lib/jenkins/workspace/gazebo-any-devel-trusty-amd64-gpu-nvidia/gazebo/test/gtest/src/gtest-death-test.cc:825:: Death tests use fork(), which is unsafe particularly in a threaded context. For this test, Google Test couldn't detect the number of threads.\r\n55: [       OK ] Exception.GZASSERT_Enabled_ThrowAssertion (1166 ms)\r\n~~~", "markup": "markdown", "html": "<p><a data-is-external-link=\"true\" href=\"http://build.osrfoundation.org/job/gazebo-any-devel-homebrew-amd64/493/testReport/(root)/Exception/GZASSERT_Enabled_ThrowAssertion/\" rel=\"nofollow\">UNIT_Exception_TEST is failing</a> on OS X consistently. Here is the console output:</p>\n<div class=\"codehilite\"><pre><span></span>55: [ RUN      ] Exception.GZASSERT_Enabled_ThrowAssertion\n55:\n55: [WARNING] /Users/jenkins/workspace/gazebo-any-devel-homebrew-amd64/gazebo/test/gtest/src/gtest-death-test.cc:825:: Death tests use fork(), which is unsafe particularly in a threaded context. For this test, Google Test detected 2 threads.\n55: /Users/jenkins/workspace/gazebo-any-devel-homebrew-amd64/gazebo/gazebo/common/Exception_TEST.cc:81: Failure\n55: Death test: (__builtin_expect(!((true == false)&amp;&amp;(&quot;Assert thrown&quot;)), 0) ? __assert_rtn(__func__, &quot;/Users/jenkins/workspace/gazebo-any-devel-homebrew-amd64/gazebo/gazebo/common/Exception_TEST.cc&quot;, 80, &quot;(true == false)&amp;&amp;(\\&quot;Assert thrown\\&quot;)&quot;) : (void)0)\n55:     Result: died but not with expected error.\n55:   Expected: .*Internal Program Error - assertion.*\n55: Actual msg:\n55: [  DEATH   ] Assertion failed: ((true == false)&amp;&amp;(&quot;Assert thrown&quot;)), function TestBody, file /Users/jenkins/workspace/gazebo-any-devel-homebrew-amd64/gazebo/gazebo/common/Exception_TEST.cc, line 80.\n55: [  DEATH   ] \n55: [  FAILED  ] Exception.GZASSERT_Enabled_ThrowAssertion (15162 ms)\n</pre></div>\n\n\n<p>On trusty, the console output looks like this:</p>\n<div class=\"codehilite\"><pre><span></span>55: [ RUN      ] Exception.GZASSERT_Enabled_ThrowAssertion\n55:\n55: [WARNING] /var/lib/jenkins/workspace/gazebo-any-devel-trusty-amd64-gpu-nvidia/gazebo/test/gtest/src/gtest-death-test.cc:825:: Death tests use fork(), which is unsafe particularly in a threaded context. For this test, Google Test couldn&#39;t detect the number of threads.\n55: [       OK ] Exception.GZASSERT_Enabled_ThrowAssertion (1166 ms)\n</pre></div>", "type": "rendered"}, "assignee": null, "state": "new", "version": {"name": "all", "links": {"self": {"href": "data/repositories/osrf/gazebo/versions/225575.json"}}}, "edited_on": null, "created_on": "2015-03-03T08:03:57.115683+00:00", "milestone": null, "updated_on": "2016-09-14T19:24:05.478228+00:00", "type": "issue", "id": 1480}