{"priority": "minor", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "links": {"attachments": {"href": "data/repositories/osrf/gazebo/issues/2710/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/gazebo/issues/2710.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gazebo/issues/2710/watch"}, "comments": {"href": "data/repositories/osrf/gazebo/issues/2710/comments_page=1.json"}, "html": {"href": "#!/osrf/gazebo/issues/2710/gazebo-7-error-cc-105-namespace-not-found"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gazebo/issues/2710/vote"}}, "reporter": {"display_name": "Shrivathsa Srikanth", "uuid": "{201cd6df-25bf-43a6-b514-06936f29dd9b}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B201cd6df-25bf-43a6-b514-06936f29dd9b%7D"}, "html": {"href": "https://bitbucket.org/%7B201cd6df-25bf-43a6-b514-06936f29dd9b%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/4bed9a98b52f1e115effe8c3871000fbd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSS-0.png"}}, "nickname": "Shrivathsa Srikanth", "type": "user", "account_id": "5e99afe4088a7e0c0f74b55e"}, "title": "Gazebo-7 error: [cc 105: namespace not found]", "component": null, "votes": 0, "watches": 0, "content": {"raw": "When I first got the \u2018namespace not found error\u2019, I didn\u2019t know what to do. I had just tried to launch gazebo straight from the terminal. Assuming it was a problem with Kubuntu, which had shown other issues, I installed Ubuntu 16.04 over it. But I saw the same error again. After hours of searching online, I found that the issue was that the required models weren\u2019t being downloaded. I fixed my problem by manually downloading the models and placing them in '/usr/share/gazebo-7/models'. \r\n\r\nThe issue was that the url from which Gazebo was trying to download the models, \u2018[http://gazebosim.org/models\u2019](http://gazebosim.org/models\u2019), is invalid. So, either the webpage has to be fixed, or the links in the \u2018setup.bash\u2019 files must be changed.", "markup": "markdown", "html": "<p>When I first got the \u2018namespace not found error\u2019, I didn\u2019t know what to do. I had just tried to launch gazebo straight from the terminal. Assuming it was a problem with Kubuntu, which had shown other issues, I installed Ubuntu 16.04 over it. But I saw the same error again. After hours of searching online, I found that the issue was that the required models weren\u2019t being downloaded. I fixed my problem by manually downloading the models and placing them in '/usr/share/gazebo-7/models'. </p>\n<p>The issue was that the url from which Gazebo was trying to download the models, \u2018<a data-is-external-link=\"true\" href=\"http://gazebosim.org/models%E2%80%99\" rel=\"nofollow\">http://gazebosim.org/models\u2019</a>, is invalid. So, either the webpage has to be fixed, or the links in the \u2018setup.bash\u2019 files must be changed.</p>", "type": "rendered"}, "assignee": null, "state": "new", "version": {"name": "7.0", "links": {"self": {"href": "data/repositories/osrf/gazebo/versions/242744.json"}}}, "edited_on": null, "created_on": "2020-04-17T13:41:04.781004+00:00", "milestone": null, "updated_on": "2020-04-17T13:41:04.781004+00:00", "type": "issue", "id": 2710}