{"priority": "minor", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "links": {"attachments": {"href": "data/repositories/osrf/gazebo/issues/730/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/gazebo/issues/730.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gazebo/issues/730/watch"}, "comments": {"href": "data/repositories/osrf/gazebo/issues/730/comments_page=1.json"}, "html": {"href": "#!/osrf/gazebo/issues/730/xacro-not-compatible-with-urdfs-sdfs"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gazebo/issues/730/vote"}}, "reporter": {"display_name": "Dave Coleman", "uuid": "{58f784f8-4b19-4221-b333-670219684927}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B58f784f8-4b19-4221-b333-670219684927%7D"}, "html": {"href": "https://bitbucket.org/%7B58f784f8-4b19-4221-b333-670219684927%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/0a0abfbe6bae9a1d65fe4af19493f423d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsDC-3.png"}}, "nickname": "Dave Coleman", "type": "user", "account_id": "557058:113fde7a-8d84-43e3-91d8-20354f36ec42"}, "title": "Xacro not compatible with URDFs->SDFs", "component": null, "votes": 0, "watches": 4, "content": {"raw": "There are conflicting tags in the Xacro format and the SDF format that is embedded into URDFs using the <gazebo> elements.\r\n\r\nBoth Xacro and SDF have <include> tags, so when Xacro sees a SDF include tag it throws an error because they have different purposes and file paths.\r\n\r\nFor example, in my dummy RRBot I am including URDF files using:\r\n\r\n```\r\n#!bash\r\n<include filename=\"$(find rrbot_description)/urdf/rrbot.gazebo\" />\r\n```\r\n\r\n\r\nAnd In the rrbot.gazebo file I am including the Hoyoku sensor using:\r\n```\r\n#!bash\r\n<include>\r\n      <uri>model://hokuyo</uri>\r\n</include> \r\n```\r\n\r\nI get the error:\r\n```\r\n#!bash\r\nTraceback (most recent call last):\r\n  File \"/opt/ros/groovy/stacks/xacro/xacro.py\", line 35, in <module>\r\n    xacro.main()\r\n  File \"/opt/ros/groovy/stacks/xacro/src/xacro.py\", line 554, in main\r\n    process_includes(doc, os.path.dirname(sys.argv[1]))\r\n  File \"/opt/ros/groovy/stacks/xacro/src/xacro.py\", line 202, in process_includes\r\n    raise XacroException(\"included file \\\"%s\\\" could not be opened: %s\" % (filename, str(e)))\r\nxacro.XacroException: included file \"/home/dave/ros/misc/src/gazebo_ros_demos/rrbot_description/urdf/\" could not be opened: [Errno 21] Is a directory: '/home/dave/ros/misc/src/gazebo_ros_demos/rrbot_description/urdf/'\r\nInvalid <param> tag: Cannot load command parameter [robot_description]: command [/opt/ros/groovy/stacks/xacro/xacro.py '/home/dave/ros/misc/src/gazebo_ros_demos/rrbot_description/urdf/rrbot.xacro'] returned with code [1]. \r\n\r\nParam xml is <param command=\"$(find xacro)/xacro.py '$(find rrbot_description)/urdf/rrbot.xacro'\" name=\"robot_description\"/>\r\n```\r\n\r\nI can get everything to work if I convert the Xacro to URDF XML first, then add the SDF include statement manually...\r\n\r\nThoughts on how to fix this?\r\n\r\nReference:\r\nhttp://ros.org/wiki/xacro#Including_other_xacro_files\r\nhttp://gazebosim.org/sdf/dev.html", "markup": "markdown", "html": "<p>There are conflicting tags in the Xacro format and the SDF format that is embedded into URDFs using the &lt;gazebo&gt; elements.</p>\n<p>Both Xacro and SDF have &lt;include&gt; tags, so when Xacro sees a SDF include tag it throws an error because they have different purposes and file paths.</p>\n<p>For example, in my dummy RRBot I am including URDF files using:</p>\n<div class=\"codehilite language-bash\"><pre><span></span>&lt;include <span class=\"nv\">filename</span><span class=\"o\">=</span><span class=\"s2\">&quot;</span><span class=\"k\">$(</span>find rrbot_description<span class=\"k\">)</span><span class=\"s2\">/urdf/rrbot.gazebo&quot;</span> /&gt;\n</pre></div>\n\n\n<p>And In the rrbot.gazebo file I am including the Hoyoku sensor using:</p>\n<div class=\"codehilite language-bash\"><pre><span></span>&lt;include&gt;\n      &lt;uri&gt;model://hokuyo&lt;/uri&gt;\n&lt;/include&gt; \n</pre></div>\n\n\n<p>I get the error:</p>\n<div class=\"codehilite language-bash\"><pre><span></span>Traceback <span class=\"o\">(</span>most recent call last<span class=\"o\">)</span>:\n  File <span class=\"s2\">&quot;/opt/ros/groovy/stacks/xacro/xacro.py&quot;</span>, line <span class=\"m\">35</span>, in &lt;module&gt;\n    xacro.main<span class=\"o\">()</span>\n  File <span class=\"s2\">&quot;/opt/ros/groovy/stacks/xacro/src/xacro.py&quot;</span>, line <span class=\"m\">554</span>, in main\n    process_includes<span class=\"o\">(</span>doc, os.path.dirname<span class=\"o\">(</span>sys.argv<span class=\"o\">[</span><span class=\"m\">1</span><span class=\"o\">]))</span>\n  File <span class=\"s2\">&quot;/opt/ros/groovy/stacks/xacro/src/xacro.py&quot;</span>, line <span class=\"m\">202</span>, in process_includes\n    raise XacroException<span class=\"o\">(</span><span class=\"s2\">&quot;included file \\&quot;%s\\&quot; could not be opened: %s&quot;</span> % <span class=\"o\">(</span>filename, str<span class=\"o\">(</span>e<span class=\"o\">)))</span>\nxacro.XacroException: included file <span class=\"s2\">&quot;/home/dave/ros/misc/src/gazebo_ros_demos/rrbot_description/urdf/&quot;</span> could not be opened: <span class=\"o\">[</span>Errno <span class=\"m\">21</span><span class=\"o\">]</span> Is a directory: <span class=\"s1\">&#39;/home/dave/ros/misc/src/gazebo_ros_demos/rrbot_description/urdf/&#39;</span>\nInvalid &lt;param&gt; tag: Cannot load <span class=\"nb\">command</span> parameter <span class=\"o\">[</span>robot_description<span class=\"o\">]</span>: <span class=\"nb\">command</span> <span class=\"o\">[</span>/opt/ros/groovy/stacks/xacro/xacro.py <span class=\"s1\">&#39;/home/dave/ros/misc/src/gazebo_ros_demos/rrbot_description/urdf/rrbot.xacro&#39;</span><span class=\"o\">]</span> returned with code <span class=\"o\">[</span><span class=\"m\">1</span><span class=\"o\">]</span>. \n\nParam xml is &lt;param <span class=\"nv\">command</span><span class=\"o\">=</span><span class=\"s2\">&quot;</span><span class=\"k\">$(</span>find xacro<span class=\"k\">)</span><span class=\"s2\">/xacro.py &#39;</span><span class=\"k\">$(</span>find rrbot_description<span class=\"k\">)</span><span class=\"s2\">/urdf/rrbot.xacro&#39;&quot;</span> <span class=\"nv\">name</span><span class=\"o\">=</span><span class=\"s2\">&quot;robot_description&quot;</span>/&gt;\n</pre></div>\n\n\n<p>I can get everything to work if I convert the Xacro to URDF XML first, then add the SDF include statement manually...</p>\n<p>Thoughts on how to fix this?</p>\n<p>Reference:\n<a href=\"http://ros.org/wiki/xacro#Including_other_xacro_files\" rel=\"nofollow\" class=\"ap-connect-link\">http://ros.org/wiki/xacro#Including_other_xacro_files</a>\n<a href=\"http://gazebosim.org/sdf/dev.html\" rel=\"nofollow\" class=\"ap-connect-link\">http://gazebosim.org/sdf/dev.html</a></p>", "type": "rendered"}, "assignee": {"display_name": "John Hsu", "uuid": "{0a186eae-abf0-4514-a951-23db5eccc286}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B0a186eae-abf0-4514-a951-23db5eccc286%7D"}, "html": {"href": "https://bitbucket.org/%7B0a186eae-abf0-4514-a951-23db5eccc286%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:f3968cd3-4910-4384-8349-482a6c7889ec/5445ce6e-6273-47f0-84eb-621c86ca11cb/128"}}, "nickname": "hsu", "type": "user", "account_id": "557058:f3968cd3-4910-4384-8349-482a6c7889ec"}, "state": "closed", "version": {"name": "all", "links": {"self": {"href": "data/repositories/osrf/gazebo/versions/225575.json"}}}, "edited_on": null, "created_on": "2013-06-07T22:31:21.285963+00:00", "milestone": null, "updated_on": "2016-09-14T19:45:18.516376+00:00", "type": "issue", "id": 730}