{"priority": "major", "kind": "bug", "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "links": {"attachments": {"href": "data/repositories/osrf/gazebo/issues/817/attachments_page=1.json"}, "self": {"href": "data/repositories/osrf/gazebo/issues/817.json"}, "watch": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gazebo/issues/817/watch"}, "comments": {"href": "data/repositories/osrf/gazebo/issues/817/comments_page=1.json"}, "html": {"href": "#!/osrf/gazebo/issues/817/gazebo-init-not-called-before-sdf-parser"}, "vote": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gazebo/issues/817/vote"}}, "reporter": {"display_name": "Paul Mathieu", "uuid": "{c5c34c75-e3ca-495f-a49a-623b1e159fca}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bc5c34c75-e3ca-495f-a49a-623b1e159fca%7D"}, "html": {"href": "https://bitbucket.org/%7Bc5c34c75-e3ca-495f-a49a-623b1e159fca%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/4808dc3f5ee7a7a70e527f4b794fd18ad=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsPM-6.png"}}, "nickname": "po1", "type": "user", "account_id": "5a42f956b7c4b33a38a18aac"}, "title": "gazebo::init() not called before SDF parser in gzfactory", "component": null, "votes": 0, "watches": 2, "content": {"raw": "Issue #769 mentions this problem, and it was solved in gzserver but not in gzfactory.\r\n\r\nHere is the message that we get when spawning a model using gzfactory in gazebo 1.9:\r\n\r\n```\r\nError [SDF.cc:118] Tried to use callback in sdf::findFile(), but the callback is empty. Did you call sdf::setFindCallback()?\r\n```\r\n\r\nSome other tools might be affected too.", "markup": "markdown", "html": "<p>Issue <a href=\"#!/osrf/gazebo/issues/769/gazebo-init-not-called-before-sdf-parser\" rel=\"nofollow\" title=\"gazebo::init() not called before SDF parser\" class=\"ap-connect-link\"><s>#769</s></a> mentions this problem, and it was solved in gzserver but not in gzfactory.</p>\n<p>Here is the message that we get when spawning a model using gzfactory in gazebo 1.9:</p>\n<div class=\"codehilite\"><pre><span></span>Error [SDF.cc:118] Tried to use callback in sdf::findFile(), but the callback is empty. Did you call sdf::setFindCallback()?\n</pre></div>\n\n\n<p>Some other tools might be affected too.</p>", "type": "rendered"}, "assignee": null, "state": "closed", "version": {"name": "all", "links": {"self": {"href": "data/repositories/osrf/gazebo/versions/225575.json"}}}, "edited_on": null, "created_on": "2013-08-27T07:48:00.981635+00:00", "milestone": null, "updated_on": "2016-09-14T19:44:19.182383+00:00", "type": "issue", "id": 817}