{"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2219/comments/34898086.json"}, "html": {"href": "#!/osrf/gazebo/issues/2219#comment-34898086"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2219.json"}}, "type": "issue", "id": 2219, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "User camera follow track_visual not working Gazebo 7.5.0"}, "content": {"raw": null, "markup": "markdown", "html": "", "type": "rendered"}, "created_on": "2017-03-06T18:51:59.808047+00:00", "user": {"display_name": "marclecerf", "uuid": "{9672692c-478d-4d44-932d-2f2ba607adff}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B9672692c-478d-4d44-932d-2f2ba607adff%7D"}, "html": {"href": "https://bitbucket.org/%7B9672692c-478d-4d44-932d-2f2ba607adff%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/4776ac21d5112999ea27675254a9df7ad=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsM-4.png"}}, "nickname": "marclecerf", "type": "user", "account_id": "557058:678ffb14-70f3-4d0f-965a-df44256d5720"}, "updated_on": null, "type": "issue_comment", "id": 34898086}