{"links": {"self": {"href": "data/repositories/osrf/gazebo/pullrequests/1341/comments/4340585.json"}, "code": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gazebo/diff/osrf/gazebo:None..None?path=test%2Fintegration%2Fplugin.cc"}, "html": {"href": "#!/osrf/gazebo/pull-requests/1341/_/diff#comment-4340585"}}, "parent": {"id": 4340495, "links": {"self": {"href": "data/repositories/osrf/gazebo/pullrequests/1341/comments/4340495.json"}, "html": {"href": "#!/osrf/gazebo/pull-requests/1341/_/diff#comment-4340495"}}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 1341, "links": {"self": {"href": "data/repositories/osrf/gazebo/pullrequests/1341.json"}, "html": {"href": "#!/osrf/gazebo/pull-requests/1341"}}, "title": "Fix INTEGRATION_plugin for gazebo_3.1 (part of #1350)"}, "content": {"raw": "Interestingly, the test passed when I ran it, and the following messages appeared in test.log:\n\n```\n(1418765790 868810022) [Err] [Model.cc:780] Exception occured in the Load function of plugin with name[exception] and filename[libExceptionModelPluginLoad.so]. This plugin will not run.\n(1418765790 869020449) Exception occured in the Load function of plugin with name[exception] and filename[libExceptionModelPluginLoad.so]. This plugin will not run.\n(1418765790 945576349) [Dbg] [ServerFixture.cc:142] ServerFixture load in 1.2 seconds, timeout after 600 seconds\n(1418765791 48259293) [Dbg] [ServerFixture.cc:93] ServerFixture::Unload\n```\n\nIt probably works because the tested plugins are ModelPlugins, and the exception occurs in `Model.cc`, not in `gazebo.cc`.", "markup": "markdown", "html": "<p>Interestingly, the test passed when I ran it, and the following messages appeared in test.log:</p>\n<div class=\"codehilite\"><pre><span></span>(1418765790 868810022) [Err] [Model.cc:780] Exception occured in the Load function of plugin with name[exception] and filename[libExceptionModelPluginLoad.so]. This plugin will not run.\n(1418765790 869020449) Exception occured in the Load function of plugin with name[exception] and filename[libExceptionModelPluginLoad.so]. This plugin will not run.\n(1418765790 945576349) [Dbg] [ServerFixture.cc:142] ServerFixture load in 1.2 seconds, timeout after 600 seconds\n(1418765791 48259293) [Dbg] [ServerFixture.cc:93] ServerFixture::Unload\n</pre></div>\n\n\n<p>It probably works because the tested plugins are ModelPlugins, and the exception occurs in <code>Model.cc</code>, not in <code>gazebo.cc</code>.</p>", "type": "rendered"}, "created_on": "2014-12-16T22:02:30.983979+00:00", "user": {"display_name": "Jackie K", "uuid": "{e3d60b62-b7c7-4863-b9b9-cdae9f123cec}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Be3d60b62-b7c7-4863-b9b9-cdae9f123cec%7D"}, "html": {"href": "https://bitbucket.org/%7Be3d60b62-b7c7-4863-b9b9-cdae9f123cec%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/ea011fa2919d4bd4568b32b440eda779d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJK-0.png"}}, "nickname": "jacquelinekay", "type": "user", "account_id": "557058:f56c822f-f75c-4665-80f9-6e7764893b9c"}, "inline": {"to": null, "from": null, "outdated": false, "path": "test/integration/plugin.cc"}, "updated_on": "2014-12-16T22:07:43.297064+00:00", "type": "pullrequest_comment", "id": 4340585}