{"pagelen": 100, "values": [{"changes": {"content": {"new": "The segmentation fault is intermittent. When it happens, it always happens after physics::Joint::Detach() is called, but not inside the caller, which is my custom function. The seg fault happens a little after my function has returned. gdb never traces t", "old": "The segmentation fault is intermittent. When it happens, it always happens after physics::Joint::Detach() is called, but not inside the caller, which is my custom function. The seg fault happens a little after my function has returned. gdb never traces t"}}, "links": {"self": {"href": "data/repositories/osrf/gazebo/issues/1815/changes/24302671.json"}, "html": {"href": "#!/osrf/gazebo/issues/1815#comment-24302671"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/1815.json"}}, "type": "issue", "id": 1815, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "Segmentation fault related to physics::Joint::Detach()"}, "created_on": "2015-12-24T08:20:48.427264+00:00", "user": {"display_name": "Mabel Zhang", "uuid": "{4b0e38fb-bf50-45c0-a496-61147518b2bf}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B4b0e38fb-bf50-45c0-a496-61147518b2bf%7D"}, "html": {"href": "https://bitbucket.org/%7B4b0e38fb-bf50-45c0-a496-61147518b2bf%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:ceb5942c-6843-408c-8550-3ce4899d299b/4d48e5ea-cf28-4fa7-9715-8fc9e315d831/128"}}, "nickname": "mabelmzhang", "type": "user", "account_id": "557058:ceb5942c-6843-408c-8550-3ce4899d299b"}, "message": {"raw": null, "markup": "markdown", "html": "", "type": "rendered"}, "type": "issue_change", "id": 24302671}, {"changes": {"content": {"new": "The segmentation fault is intermittent. When it happens, it always happens after physics::Joint::Detach() is called, but not inside the caller, which is my custom function. The seg fault happens a little after my function has returned. gdb never traces t", "old": "The segmentation fault is intermittent. When it happens, it always happens after physics::Joint::Detach() is called, but not inside the caller, which is my custom function. The seg fault happens a little after my function has returned. gdb never traces t"}}, "links": {"self": {"href": "data/repositories/osrf/gazebo/issues/1815/changes/24302681.json"}, "html": {"href": "#!/osrf/gazebo/issues/1815#comment-24302681"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/1815.json"}}, "type": "issue", "id": 1815, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "Segmentation fault related to physics::Joint::Detach()"}, "created_on": "2015-12-24T08:21:16.612620+00:00", "user": {"display_name": "Mabel Zhang", "uuid": "{4b0e38fb-bf50-45c0-a496-61147518b2bf}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B4b0e38fb-bf50-45c0-a496-61147518b2bf%7D"}, "html": {"href": "https://bitbucket.org/%7B4b0e38fb-bf50-45c0-a496-61147518b2bf%7D/"}, "avatar": {"href": "https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/557058:ceb5942c-6843-408c-8550-3ce4899d299b/4d48e5ea-cf28-4fa7-9715-8fc9e315d831/128"}}, "nickname": "mabelmzhang", "type": "user", "account_id": "557058:ceb5942c-6843-408c-8550-3ce4899d299b"}, "message": {"raw": null, "markup": "markdown", "html": "", "type": "rendered"}, "type": "issue_change", "id": 24302681}], "page": 1, "size": 2}