{"links": {"self": {"href": "data/repositories/osrf/gazebo/pullrequests/1743/comments/7716613.json"}, "html": {"href": "#!/osrf/gazebo/pull-requests/1743/_/diff#comment-7716613"}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 1743, "links": {"self": {"href": "data/repositories/osrf/gazebo/pullrequests/1743.json"}, "html": {"href": "#!/osrf/gazebo/pull-requests/1743"}}, "title": "Added laser lines to laser visualization (default)"}, "content": {"raw": "I get seg-faults when I insert a hokuyo into a world that has objects within range:\n\n~~~\n[Err] [DynamicLines.cc:86] EXCEPTION: Point index[537] is out of bounds[0-536]\n\nQt has caught an exception thrown from an event handler. Throwing\nexceptions from an event handler is not supported in Qt. You must\nreimplement QApplication::notify() and catch all exceptions there.\n\nterminate called after throwing an instance of 'gazebo::common::Exception'\n\nProgram received signal SIGABRT, Aborted.\n0x00007ffff671acc9 in __GI_raise (sig=sig@entry=6)\n    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56\n56\t../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.\n(gdb) bt\n#0  0x00007ffff671acc9 in __GI_raise (sig=sig@entry=6)\n    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56\n#1  0x00007ffff671e0d8 in __GI_abort () at abort.c:89\n#2  0x00007ffff6d1f535 in __gnu_cxx::__verbose_terminate_handler() ()\n   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6\n#3  0x00007ffff6d1d6d6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6\n#4  0x00007ffff6d1d703 in std::terminate() ()\n   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6\n#5  0x00007ffff6d1d976 in __cxa_rethrow ()\n   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6\n#6  0x00007ffff7343596 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4\n#7  0x00007ffff7348b79 in QCoreApplication::exec() ()\n   from /usr/lib/x86_64-linux-gnu/libQtCore.so.4\n#8  0x00007ffff7772cdb in gazebo::gui::run (_argc=_argc@entry=2, \n    _argv=_argv@entry=0x7fffffffdc98)\n    at /home/scpeters/ws/gazebo/src/gazebo/gazebo/gui/GuiIface.cc:308\n#9  0x00000000004014ea in main (_argc=2, _argv=0x7fffffffdc98)\n    at /home/scpeters/ws/gazebo/src/gazebo/gazebo/gui/main.cc:25\n(gdb)\n~~~\n\nNote that I don't get a seg-fault if I insert the hokuyo and then insert a box within its range after the visualization has appeared.\n\nAlso, I get a seg-fault when loading `test/worlds/laser_vertical.world`; it may be the same root cause as the first test case.", "markup": "markdown", "html": "<p>I get seg-faults when I insert a hokuyo into a world that has objects within range:</p>\n<div class=\"codehilite\"><pre><span></span><span class=\"k\">[Err] [DynamicLines.cc:86] EXCEPTION: Point index[537] is out of bounds[0-536]</span>\n\n<span class=\"na\">Qt has caught an exception thrown from an event handler. Throwing</span>\n<span class=\"na\">exceptions from an event handler is not supported in Qt. You must</span>\n<span class=\"na\">reimplement QApplication::notify() and catch all exceptions there.</span>\n\n<span class=\"na\">terminate called after throwing an instance of &#39;gazebo::common::Exception&#39;</span>\n\n<span class=\"na\">Program received signal SIGABRT, Aborted.</span>\n<span class=\"na\">0x00007ffff671acc9 in __GI_raise (sig</span><span class=\"o\">=</span><span class=\"s\">sig@entry=6)</span>\n<span class=\"s\">    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56</span>\n<span class=\"na\">56  ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.</span>\n<span class=\"na\">(gdb) bt</span>\n<span class=\"c1\">#0  0x00007ffff671acc9 in __GI_raise (sig=sig@entry=6)</span>\n    <span class=\"na\">at ../nptl/sysdeps/unix/sysv/linux/raise.c:56</span>\n<span class=\"c1\">#1  0x00007ffff671e0d8 in __GI_abort () at abort.c:89</span>\n<span class=\"c1\">#2  0x00007ffff6d1f535 in __gnu_cxx::__verbose_terminate_handler() ()</span>\n   <span class=\"na\">from /usr/lib/x86_64-linux-gnu/libstdc++.so.6</span>\n<span class=\"c1\">#3  0x00007ffff6d1d6d6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6</span>\n<span class=\"c1\">#4  0x00007ffff6d1d703 in std::terminate() ()</span>\n   <span class=\"na\">from /usr/lib/x86_64-linux-gnu/libstdc++.so.6</span>\n<span class=\"c1\">#5  0x00007ffff6d1d976 in __cxa_rethrow ()</span>\n   <span class=\"na\">from /usr/lib/x86_64-linux-gnu/libstdc++.so.6</span>\n<span class=\"c1\">#6  0x00007ffff7343596 in QEventLoop::exec(QFlags&lt;QEventLoop::ProcessEventsFlag&gt;) () from /usr/lib/x86_64-linux-gnu/libQtCore.so.4</span>\n<span class=\"c1\">#7  0x00007ffff7348b79 in QCoreApplication::exec() ()</span>\n   <span class=\"na\">from /usr/lib/x86_64-linux-gnu/libQtCore.so.4</span>\n<span class=\"c1\">#8  0x00007ffff7772cdb in gazebo::gui::run (_argc=_argc@entry=2, </span>\n    <span class=\"na\">_argv</span><span class=\"o\">=</span><span class=\"s\">_argv@entry=0x7fffffffdc98)</span>\n<span class=\"s\">    at /home/scpeters/ws/gazebo/src/gazebo/gazebo/gui/GuiIface.cc:308</span>\n<span class=\"c1\">#9  0x00000000004014ea in main (_argc=2, _argv=0x7fffffffdc98)</span>\n    <span class=\"na\">at /home/scpeters/ws/gazebo/src/gazebo/gazebo/gui/main.cc:25</span>\n<span class=\"na\">(gdb)</span>\n</pre></div>\n\n\n<p>Note that I don't get a seg-fault if I insert the hokuyo and then insert a box within its range after the visualization has appeared.</p>\n<p>Also, I get a seg-fault when loading <code>test/worlds/laser_vertical.world</code>; it may be the same root cause as the first test case.</p>", "type": "rendered"}, "created_on": "2015-06-22T23:28:45.833919+00:00", "user": {"display_name": "Steve Peters", "uuid": "{2ccfed09-18b8-4921-8d58-15ef01092802}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D"}, "html": {"href": "https://bitbucket.org/%7B2ccfed09-18b8-4921-8d58-15ef01092802%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/1fb4816dad9e68337d3096f750951f6cd=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsSP-1.png"}}, "nickname": "Steven Peters", "type": "user", "account_id": "557058:5de38267-b118-494c-aa76-4fab35448816"}, "updated_on": "2015-06-22T23:28:45.839882+00:00", "type": "pullrequest_comment", "id": 7716613}