{"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/1204/comments/11258712.json"}, "html": {"href": "#!/osrf/gazebo/issues/1204#comment-11258712"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/1204.json"}}, "type": "issue", "id": 1204, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "Trusty: remote_endpoint: Transport endpoint is not connected"}, "content": {"raw": "Is this expected to be fixed in the latest 2.2 deb? I'm having this issue with the 1.54.0-4ubuntu3.1 version of boost-mpi and 2.2.2-6 of gazebo. ", "markup": "markdown", "html": "<p>Is this expected to be fixed in the latest 2.2 deb? I'm having this issue with the 1.54.0-4ubuntu3.1 version of boost-mpi and 2.2.2-6 of gazebo. </p>", "type": "rendered"}, "created_on": "2014-07-16T01:35:04.212838+00:00", "user": {"display_name": "Brian Axelrod", "uuid": "{2a2fa192-0104-45dd-b42d-ad260be7402b}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B2a2fa192-0104-45dd-b42d-ad260be7402b%7D"}, "html": {"href": "https://bitbucket.org/%7B2a2fa192-0104-45dd-b42d-ad260be7402b%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/a70afebbb46bad6187bc6628b7ccc319d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsBA-1.png"}}, "nickname": "brianaxelrod", "type": "user", "account_id": "557058:f3397300-1cd7-4004-8029-98a62ebe1688"}, "updated_on": "2014-07-16T01:35:55.820089+00:00", "type": "issue_comment", "id": 11258712}