{"links": {"self": {"href": "data/repositories/osrf/gazebo/pullrequests/1202/comments/3205867.json"}, "code": {"href": "https://api.bitbucket.org/2.0/repositories/osrf/gazebo/diff/osrf/gazebo:d681743fca08..e5ebed9be0e5?path=test%2Fregression%2Fplugin.cc"}, "html": {"href": "#!/osrf/gazebo/pull-requests/1202/_/diff#comment-3205867"}}, "deleted": false, "pullrequest": {"type": "pullrequest", "id": 1202, "links": {"self": {"href": "data/repositories/osrf/gazebo/pullrequests/1202.json"}, "html": {"href": "#!/osrf/gazebo/pull-requests/1202"}}, "title": "Added exception handling to model plugins"}, "content": {"raw": "I would say that the gtest feature ```ASSERT_NO_THROW``` fits perfect this kind of testing. We could surround all the Load calls in these tests.", "markup": "markdown", "html": "<p>I would say that the gtest feature <code>ASSERT_NO_THROW</code> fits perfect this kind of testing. We could surround all the Load calls in these tests.</p>", "type": "rendered"}, "created_on": "2014-09-24T23:57:18.968268+00:00", "user": {"display_name": "Jose Luis Rivero", "uuid": "{d12309b2-f745-42ee-b119-aec4fcdf81fe}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D"}, "html": {"href": "https://bitbucket.org/%7Bd12309b2-f745-42ee-b119-aec4fcdf81fe%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/109284c8b83411dbc7492138f6167e9ed=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsJR-5.png"}}, "nickname": "Jose Luis Rivero", "type": "user", "account_id": "557058:155a32e2-420c-4d50-98e0-0e722f63f906"}, "inline": {"to": 29, "from": null, "outdated": false, "path": "test/regression/plugin.cc"}, "updated_on": "2014-09-24T23:57:18.975026+00:00", "type": "pullrequest_comment", "id": 3205867}