{"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2481/comments/52920325.json"}, "html": {"href": "#!/osrf/gazebo/issues/2481#comment-52920325"}}, "issue": {"links": {"self": {"href": "data/repositories/osrf/gazebo/issues/2481.json"}}, "type": "issue", "id": 2481, "repository": {"links": {"self": {"href": "data/repositories/osrf/gazebo.json"}, "html": {"href": "#!/osrf/gazebo"}, "avatar": {"href": "data/bytebucket.org/ravatar/{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}ts=1694483"}}, "type": "repository", "name": "gazebo", "full_name": "osrf/gazebo", "uuid": "{51a0cd5d-8697-4eb1-8b08-e919ee881e1c}"}, "title": "7.13.0 debbuilds failed on trusty"}, "content": {"raw": "Hello,\n\nI tried to install Gazebo 7 on trusty and I have the same issue with copy\\_file\\(\\) but called from another file.\n\n``util/libgazebo_util.so.7.15.0: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option, boost::system::error_code*)'``  \n`collect2: error: ld returned 1 exit status`  \n`make[2]: *** [gazebo/gzserver-7.15.0] Error 1`  \n`make[1]: *** [gazebo/CMakeFiles/gzserver.dir/all] Error 2`  \n`make: *** [all] Error 2`\n\nI don\u2019t know if this issue is related to the same error. I used the branch of gazebo7 as written in the installation file. Should I take another one ? \n\nFor instance this one gazebo7-fix-boost-compile-error ? Update: I tried this one and I got this error:\n\n``libgazebo_common.so.7.13.0: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option, boost::system::error_code*)'``  \n`collect2: error: ld returned 1 exit status`  \n`make[2]: *** [gazebo/common/UNIT_Mesh_TEST] Error 1`  \n`make[1]: *** [gazebo/common/CMakeFiles/UNIT_Mesh_TEST.dir/all] Error 2`\n\nBest regards,", "markup": "markdown", "html": "<p>Hello,</p>\n<p>I tried to install Gazebo 7 on trusty and I have the same issue with copy_file() but called from another file.</p>\n<p><code>util/libgazebo_util.so.7.15.0: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&amp;, boost::filesystem::path const&amp;, boost::filesystem::copy_option, boost::system::error_code*)'</code><br />\n<code>collect2: error: ld returned 1 exit status</code><br />\n<code>make[2]: *** [gazebo/gzserver-7.15.0] Error 1</code><br />\n<code>make[1]: *** [gazebo/CMakeFiles/gzserver.dir/all] Error 2</code><br />\n<code>make: *** [all] Error 2</code></p>\n<p>I don\u2019t know if this issue is related to the same error. I used the branch of gazebo7 as written in the installation file. Should I take another one ? </p>\n<p>For instance this one gazebo7-fix-boost-compile-error ? Update: I tried this one and I got this error:</p>\n<p><code>libgazebo_common.so.7.13.0: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&amp;, boost::filesystem::path const&amp;, boost::filesystem::copy_option, boost::system::error_code*)'</code><br />\n<code>collect2: error: ld returned 1 exit status</code><br />\n<code>make[2]: *** [gazebo/common/UNIT_Mesh_TEST] Error 1</code><br />\n<code>make[1]: *** [gazebo/common/CMakeFiles/UNIT_Mesh_TEST.dir/all] Error 2</code></p>\n<p>Best regards,</p>", "type": "rendered"}, "created_on": "2019-07-10T07:03:02.378885+00:00", "user": {"display_name": "Deastan", "uuid": "{4e2f872a-2e95-440a-b397-75a97b4efba0}", "links": {"self": {"href": "https://api.bitbucket.org/2.0/users/%7B4e2f872a-2e95-440a-b397-75a97b4efba0%7D"}, "html": {"href": "https://bitbucket.org/%7B4e2f872a-2e95-440a-b397-75a97b4efba0%7D/"}, "avatar": {"href": "data/secure.gravatar.com/avatar/73e0a26db3d2efdb19d9421d53b66b05d=httpsavatar-management--avatars.us-west-2.prod.public.atl-paas.netinitialsD-0.png"}}, "nickname": "Deastan", "type": "user", "account_id": "5d24bfa1cc39bc0c2b5b9979"}, "updated_on": "2019-07-10T07:17:34.217556+00:00", "type": "issue_comment", "id": 52920325}